trigger:
  branches:
    include:
      - master
      - refs/tags/*
  paths:
    exclude:
      - README.md
      - NOTICE

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - azure-pipelines.yml
      - README.md
      - NOTICE

resources:
  repositories:
    - repository: templates
      type: github
      name: duchessa/azure-pipelines-templates
      endpoint: github.com_beautyandbellies-dev

extends:
  template: sbt-parent_bintray_publish.yml@templates
  parameters:
    publishOptionsVariableGroup: 'duchessa-devops'
    bintrayOrganisation: 'duchessa'
    bintrayRepository: 'sbt-plugins'
